### ISSUE TITLE
Preliminary support for `@CitrusTestFactory` annotation

### ISSUE THREAD

**Issue by picimako** [picimako/citric#11]
### Tasks
- [x] Add an action into the Alt+Insert Generate menu to be able to generate `@CitrusTestFactory` annotated Citrus JUnit5 test methods.
- Create inspections for the annotation, if any necessary.
  - Based on https://junit.org/junit5/docs/5.5.1/api/org/junit/jupiter/api/TestFactory.html
    - [x] `@CitrusTestFactory` methods must not be private or static
    - [x] `@CitrusTestFactory` methods must have the proper return types
  - [x] `@CitrusTestFactory` annotated method doesn't need the JUnit `@TestFactory` annotation.
- [x] Extend existing inspections to handle and take into account this annotation.

### Resources
- https://junit.org/junit5/docs/current/user-guide/#writing-tests-dynamic-tests
- https://junit.org/junit5/docs/5.5.1/api/org/junit/jupiter/api/TestFactory.html
- https://www.baeldung.com/junit5-dynamic-tests

**Comment by picimako** [comment]
Completed in v1.0.4.
