### ISSUE TITLE
Check and add support for Citrus 4.2.0

### ISSUE THREAD

**Issue by picimako** [picimako/citric#31]
### Summary

Citrus 4.2.0 is out, so let's check its changes and support the ones we can.

### Tasks
- [Test sharding](https://github.com/citrusframework/citrus/commit/6840b5b8dcb8de690844f03d28c85d3dad666c13)
  - [x] Code completion of new system properties in `citrus-application.properties`:
    - Properties: citrus.sharding.total, citrus.sharding.number, citrus.sharding.seed
    - Description of them are available in the javadoc of the `ShardingConfiguration` class.
    - These properties must be completed only when Citrus 4.2.0 is available in the project. The same solution may be used as for CLI command completion in WireMocha.
  - [x] Inspections:
    - `citrus.sharding.number`: This should be a value between 0 and the total number of shards minus one.
      - [x] Report less than 0 values.
      - [x] If `citrus.sharding.total` is specified in the citrus-application.properties, report invalid max numbers according to that value.
    - [x] Total number of shards must be at least 1.

### Resources
- [Release](https://github.com/citrusframework/citrus/releases/tag/v4.2.0)
- [File changes since 4.1.1](https://github.com/citrusframework/citrus/compare/v4.1.1...v4.2.0)

**Comment by picimako** [comment]
Completed in v1.0.7.
