### ISSUE TITLE
Look into `@CitrusSpringXmlTestFactory` and `CitrusTestFactorySupport`

### ISSUE THREAD

**Issue by picimako** [picimako/citric#32]
### Summary

`CitrusTestFactorySupport` is a fairly new solution, while `@CitrusSpringXmlTestFactory` has been around. Look into how they are processed and should be used, and implement integrations for them.

### Tasks
- `CitrusTestFactorySupport`
  - [x] Line marker for CitrusTestFactorySupport.[springXml()|xml()|groovy()].[dynamicTest()|packageScan()|etc.] calls to navigate to the referenced resources.
    - This would work the same as the line marker for `@CitrusTestSource` test methods.
  - [x] Inspection and quick fixes to replace `.factory(...)` calls to `.xml()`, `.springXml()` or `.groovy()` calls.
  - [x] Inspection to report invalid test types in `.factory(...)`.
  - [x] Inspection to report file extensions in test names inside `CitrusTestFactorySupport.dynamicTest[s]()`.
    - This is not required for groovy tests.
  - [x] Inspection to report `dynamicTests()` with no test name provided.
  - [x] Inspection to report `packageScan()` with no package name provided.
- `@CitrusSpringXmlTestFactory`
  - [x] Inspection: if a non-`CitrusTestFactorySupport.springXml()` method is called in a test method annotated with `@CitrusSpringXmlTestFactory`, then the annotation must be reported because it may mislead users about the contents of the test method.
  - [x] Update the `@CitrusTestFactory` annotation related inspection to support `@CitrusSpringXmlTestFactory` as well.
  - [x] Create a Generate `@CitrusSpringXmlTestFactory Method` action based on the `@CitrusTestFactory Method` action.
    - This action should be available only when the citrus-junit5 package is available.

**Comment by picimako** [comment]
Completed in v1.0.12.
