### ISSUE TITLE
Language injections in XML and Spring XML DSLs

### ISSUE THREAD

**Issue by picimako** [picimako/citric#46]
### Summary

There are many XML attributes that accept expressions of XPath, JsonPath, and many other languages. Those attribute values could be injected with the proper languages.

### Tasks
Add language injection for following XML tag attributes:
- [x] JsonPath:
  - [x] in `k8s:validate.k8s:element@path` in 'http://www.citrusframework.org/schema/kubernetes/testcase'
  - [x] in `message.expression@path` in XML when the sibling `message` tag's `type` attribute is *json*
  - [x] in `message.validate.json-path@expression` in Spring XML
  - [x] in `zookeeper:info.zookeeper:validate.zookeeper:json-path@expression` in 'http://www.citrusframework.org/schema/zookeeper/testcase'
- [x] XPath:
  - [x] in `receive.validate.xpath@expression` in XMLs
  - [x] in `receive.message.validate.xpath@expression` in Spring XMLs
- [x] Regex:
  - [x] in `step@given/when/then` in 'http://www.citrusframework.org/schema/cucumber/testcase'
- [x] Groovy
  - [x] in `actions/template.groovy` in XML and Spring XML DSLs
  - [x] in `actions.send/receive.message.builder` when the `type` attribute is set to *groovy* in Spring XMLs
  - [x] in `variables/create-variables.variable.value.script` when the `type` attribute is set to *groovy* in XML and Spring XML DSLs
  - [x] in `message.validate.script` when its `type` attribute is *groovy* in Spring XMLs
  - [x] in `sql.validate.script` when its `type` attribute is *groovy* in Spring XMLs
- [x] XML:
  - [x] in `transform.xml-data/xslt-data` in Spring
  - [x] in `transform.source/xslt` in non-Spring
- [x] JavaScript:
  - [x] in `selenium:javascript.selenium:script`
- [x] JSON:
  - [x] in `selenium.fill-form.json` in non-Spring XMLs

**Comment by picimako** [comment]
Completed in v1.0.16.
