### ISSUE TITLE
Extend the list of XML attributes to show resource line markers

### ISSUE THREAD

**Issue by picimako** [picimako/citric#47]
### Summary

There are already line markers in the XML and Spring XML DSLs on attributes that accept Citrus resource paths. This issue is to extend the list of supported tags and attributes.

### Tasks
- Add the line marker to:
  - [x] global-variables.file@path in context XML (http://www.citrusframework.org/schema/config)
  - [x] repository.schemas.schema@location
  - [x] schema-collection.schemas.schema@location
  - [x] citrus-ftp:server@user-manager-properties in context XML (http://www.citrusframework.org/schema/ftp/config)
  - [x] citrus-scp:client@private-key-path in context XML (http://www.citrusframework.org/schema/scp/config)
  - [x] citrus-sftp:client@private-key-path, citrus-sftp:client@known-hosts-path in context XML (http://www.citrusframework.org/schema/sftp/config)
  - [x] citrus-sftp:server@allowed-key-path, citrus-sftp:server@host-key-path in context XML (http://www.citrusframework.org/schema/sftp/config)
  - [x] http:server@context-config-location in context XML (http://www.citrusframework.org/schema/http/config)
  - [x] citrus:schema@location in context XML (http://www.citrusframework.org/schema/config)
  - [x] k8s:create-pod.k8s:template@file in Spring (http://www.citrusframework.org/schema/kubernetes/testcase)
  - [x] k8s:create-service.k8s:template@file in Spring (http://www.citrusframework.org/schema/kubernetes/testcase)
  - [x] citrus-ssh:server@allowed-key-path/host-key-path in context XML (http://www.citrusframework.org/schema/ssh/config)
  - [x] citrus-ssh:client@private-key-path/known-hosts-path in context XML (http://www.citrusframework.org/schema/ssh/config)
  - [x] wait.file@path in Spring
  - [x] citrus:json-data-dictionary/citrus:xml-data-dictionary.mapping-file@path in Spring
  - [x] ws:assert-fault.fault-detail@file in Spring (http://www.citrusframework.org/schema/ws/testcase)
  - [x] testcase.variables.variable@value in Spring

**Comment by picimako** [comment]
Completed in v1.0.14.
