### ISSUE TITLE
Add support for Citrus 4.4.0

### ISSUE THREAD

**Issue by picimako** [picimako/citric#61]
### Summary

Look into the [Citrus 4.4.0](https://github.com/citrusframework/citrus/releases/tag/v4.4.0) release and add support for changes if necessary.

### Tasks
- https://github.com/citrusframework/citrus/commit/057f25214285bd4bceae996fda45b70364b94071 (JAVA, XML)
  - See if the changes in `KafkaEndpointParser` needs any work on Citric side, and see what the `random-consumer-group` XML attribute does in `citrus-kafka-config.xsd`.
    - [x] Inspection: either only the `random-consumer-group` or the `consumer-group` XML attribute must be specified at a time but not both. (Based on the logic in `KafkaEndpointParser`.)
  - [x] Code completion of message selectors from `org.citrusframework.kafka.endpoint.selector.KafkaMessageByHeaderSelector` and `org.citrusframework.kafka.endpoint.KafkaMessageFilter`.
  - [x] Code completion of `org.citrusframework.kafka.endpoint.selector.KafkaMessageByHeaderSelector.ValueMatchingStrategy` values in message selectors in case of `header-filter-comparator`.
- [x] https://github.com/citrusframework/citrus/commit/ca50d7ed4c61d49fe207dbdd0d28679d33570d31 (All DSLs.)
  - Add support for the `isUUIDv4` validation matcher. 
- [x] https://github.com/citrusframework/citrus/commit/bab5347632e1c391022ccf1bbed749bc25033d88 (JAVA DSL)
  - Default builder method argument value reporting.
- https://github.com/citrusframework/citrus/commit/578595a540853217eae03f235ae8b8f769d894c4
  - [x] Handle the new `timeout` in all iterating containers based on `AbstractIteratingContainerBuilder.java`.
  - [x] `RepeatOnErrorUntilTrue`: `autoSleep` has changed from `Long` to `Duration` in the JAVA DSL
  - XML:
    - `AbstractIteratingTestContainerFactoryBean.java`: it received a `setTimeout()` method
    - `citrus-testcase.xsd`: the new `timeout` attributes are added as String.

### Notes
- Code completion of non-Kafka related message selector names will be the scope of a separate issue.

**Comment by picimako** [comment]
Completed in v1.0.19.
