### ISSUE TITLE
Inspections for the @CitrusTestSource annotation

### ISSUE THREAD

**Issue by picimako** [picimako/citric#7]
### Summary

Certain issues could be detected by static analysing the configuration of `@CitrusTestSource` annotations.

### Tasks
- Create an inspection that can detect the following:
  - [x] invalid test type
  - [x] if a value in `name` is the same as the test method's name, the value from `name` can be removed.
  - [x] if `packageName` is the same as the package of the current test class, the `packageName` attribute can be removed.
  - [x] the file extension associated with the test `type` must not be specified at the end of the values in `name`.
  - [x] the file extensions in `sources` must match the file extension of the test type in `type`.
  - [x] the same files in `name` and `sources` may be deduplicated.

**Comment by picimako** [comment]
Completed in v1.0.3.
