### ISSUE TITLE
Citrus Quarkus support

### ISSUE THREAD

**Issue by picimako** [picimako/citric#8]
### Summary

Citrus v4 add Quarkus runtime support.

### Tasks
- [x] Introduce JUnit5 specific Citrus Quarkus test framework.
- [x] Inspection: If the test class is annotated with `@org.citrusframework.quarkus.CitrusSupport` but not with `@QuarkusTest`, then it is probably an issue to report.
- [x] Inspection: A test class annotated with `@QuarkusTest` but not with `@org.citrusframework.quarkus.CitrusSupport`, and when the class has Citrus specific injected fields like `@CitrusFramework`, `@BindToRegistry`, etc. then the class must be reported to be annotated as `@CitrusSupport` too.
- [x] Inspection: report `@com.consol.citrus/org.citrusframework.junit.jupiter.CitrusSupport` used on a `@QuarkusTest` annotated test class, instead of `@org.citrusframework.quarkus.CitrusSupport`.

**Comment by picimako** [comment]
Completed in v1.0.4.
