### ISSUE TITLE
Inspections around injected Citrus resources

### ISSUE THREAD

**Issue by picimako** [picimako/citric#9]
### Summary

There are various types of resources that can be injected by Citrus, like `Citrus`, `TestCaseRunner`, endpoints, and others.

In order to identify usage issues earlier, one or more inspections could be useful.

### Tasks
- Create one or more inspections with the following checks:
  - [x] A field is annotated with `@CitrusFramework` but the field type is not `Citrus`.
    - This prevents injecting the `Citrus` object into the field.
  - [x] A field is annotated with `@CitrusEndpoint` but the field type is not `Endpoint` or one of its inheritors.
    - This prevents injecting an `Endpoint` object into the field.
  - [x] A field is annotated with one of the `@*EndpointConfig` annotations but it is not annotated with `@CitrusEndpoint`.
    - This prevents injecting an `Endpoint` object into the field, and then be able to override its properties.
  - [x] A field has as type one of the inheritors of `Endpoint` but the `@*EndpointConfig` annotation on the field doesn't match the type.
    -  E.g. `DirectEndpoint` field annotated with `@CamelEndpointConfig`.

**Comment by picimako** [comment]
Completed in v1.0.4.
